config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  scope :most_recent, -> { order(created_at: :desc).limit(3)}
  scope :most_reviews, -> {(
    select("products.name, count(products.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}
  scope :local, -> { where(country_of_origin: "United States") }

  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates_numericality_of :cost
  validates :country_of_origin, presence: true

  before_save(:titleize_product)

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :rating, presence: true
  validates_numericality_of :rating, greater_than_or_equal_to: 1
  validates_numericality_of :rating, less_than_or_equal_to: 5
  validates :content_body, presence: true, length: { minimum: 50, maximum: 250 }
  validates :product_id, presence: true

  before_save(:titleize_author)

  private
    def titleize_author
      self.author = self.author.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def autherize_admin
    if signed_in? == false
      flash[:alert] = 'Please sign in to continue'
      if request.referrer == nil
        redirect_to root_path
      else
        redirect_to request.referrer
      end
    end

    if signed_in? == true
      if current_user.admin != true
        flash[:alert] = "You aren't authorized to perform this action"
      if request.referrer == nil
        redirect_to root_path
      else
        redirect_to request.referrer
       end
      end
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:admin, :user, :email, :password)}


    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :edit] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @products = Product.all
    @most_reviewed = Product.most_reviews
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added! One more than Luigi has!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:alert] = "Product was deleted to keep the princess safe!"
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:edit] do
    redirect_to product_review_path unless current_user && current_user.admin
  end  
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added! It had better be positive!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      @product = Product.find(params[:product_id])
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:alert] = "The customer isn't always right!"
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to Mario's Fine Foods</h1>
<h4>Bowser's favorite shoppe</h4>
<p class='home_link'><%= link_to "Check out our products", products_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit  %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MariosFineFoods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
    <%= flash[:alert] %>
    <%= flash[:notice] %>


    <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Products</h1>


<% if @products.any? %>
  <ul>
    <h3>Newest Products</h3>
      <% @products.most_recent.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <%end%>

    <h3>Local Products</h3>
      <%if @products.local.any?%>
        <% @products.local.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <%end%>
      <% else %>
        <p>There are no local products at this time.</p>
      <% end %>

    <h3>Most Reviewed Product</h3>
      <% @products.most_reviews.each do |product| %>
        <li><%= product.name %></li>
      <%end%>

    <h3>All Products</h3>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

<% if current_user && current_user.admin %>
<p><%= link_to "Add new product", new_product_path %></p>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>$ <%= @product.cost %></h3>
<h3><%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
  <h5>Here are the reviews for this product:</h5>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<% if current_user && current_user.admin %>
<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<% end %>
<p><%= link_to "Return to products page", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a new review:</h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :rating %>
  <%= f.text_area :rating %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/show.html.erb
<h1>Product: <%= @product.name %></h1>
<h2>Reviewer: <%= @review.author %></h2>
<h3><%= @review.rating %>/5</h3>
<h3><%= @review.content_body %></h3>

<% if current_user && current_user.admin %>
<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<% end %>
<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Mario's Foods</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>